dist: xenial
language: python
python: 3.6

install: true

script: true

deploy:

  # Development / test deployment
  - provider: pypi
    skip_cleanup: true
    user: aleg
    password: "$PYPI_PW"
    server: https://test.pypi.org/legacy/
    on:
      all_branches: true
      tags: true
      condition: $TRAVIS_TAG == *.dev*

  - provider: script
    skip_cleanup: true
    script: bash ./deploy_anaconda.sh $ANACONDA_DEV_TOKEN
    on:
      all_branches: true
      tags: true
      condition: $TRAVIS_TAG == *.dev*


  # Production version deployment
  - provider: pypi
    skip_cleanup: true
    user: aleg
    password: "$PYPI_PW"
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_TAG != *.dev*

  - provider: script
    skip_cleanup: true
    script: bash ./deploy_anaconda.sh $ANACONDA_TOKEN
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_TAG != *.dev*

  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_TAG != *.dev*
