package:
  name: {{ versipy|lower }}
  version: {{ 3.1.0.dev1 }}

source:
  path: dist/{{ versipy }}-{{ 3.1.0.dev1 }}.tar.gz

build:
  number: 0
  script: "pip install {{ versipy }}-{{ 3.1.0.dev1 }}.tar.gz --no-deps --ignore-installed -vv"
  entry_points:
    - versipy=versipy.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=>=3.6
    - pip>=19.2.1
    - ripgrep>=11.0.1
  run:
    - colorlog>=4.1.0
    - pyyaml>=5.3.1

about:
  home: https://github.com/a-slide/versipy
  license: MIT
  summary: Simple python version managment in source code, git and across packaging ecosystem
  
extra:
  author: Adrien Leger
  email: contact AT adrienleger DOT com