package:
  name: {{ __name__|lower }}
  version: __version__

source:
  path: dist/__name__-__version__.tar.gz

build:
  number: 0
  script: "pip install __name__-__version__.tar.gz --no-deps --ignore-installed -vv"
  entry_points:
    - __entry_point1__
  noarch: "python"

requirements:
  build:
    - python>=__minimal_python__
    - pip>=19.2.1
    - ripgrep>=11.0.1
  run:
    - __dependency1__
    - __dependency2__
    - __dependency3__
about:
  home: __url__
  license: __licence__
  licence_url: __licence_url__
  summary: __description__

extra:
  author: __author__
  author_email: __author_email__
  author_url: __author_url__
