{% set version = "__version__" %}
{% set name = "__name__" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "

  entry_points:
    - __entry_point1__
  noarch: "python"

requirements:
  build:
    - python__minimal_python__
    - pip>=19.2.1
    - ripgrep>=11.0.1
  run:
    - __dependency1__
    - __dependency2__
    - __dependency3__
about:
  home: __url__
  license: __licence__
  licence_url: __licence_url__
  summary: __description__

extra:
  author: __author__
  author_email: __author_email__
  author_url: __author_url__
